// generated by mBlock5 for mBot
// codes make you happy

#include <MeMCore.h>
#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>

MeUltrasonicSensor ultrasonic(3);
MeLineFollower linefollower(1);
MeBuzzer buzzer;
MeRGBLed led(7, 2);
// 0 is both leds, 1 is right, 2 is left

void _loop();
void parseCommand(String cmd);

void _delay(float seconds) {
  long endTime = millis() + seconds * 1000;
  while(millis() < endTime) _loop();
}

void setup() {
  Serial.begin(57600);
  led.fillPixelsBak(0, 2, 1);
}

void loop() {
  if(Serial.available() > 0) {
    String input = Serial.readStringUntil('\n');
    parseCommand(input);
  }
}

void parseCommand(String cmd) {
  cmd.trim();

  if(cmd.startsWith("/color")) {
    String params = cmd.substring(7);

    int led_index = 0;
    int r = 0, g = 0, b = 0;

    int count = sscanf(params.c_str(), "%d %d %d %d", &led_index, &r, &g, &b);

    if(count >= 4) {
      led.setColor(led_index, r, g, b);
      led.show();
      Serial.print("Set LED ");
      Serial.print(led_index);
      Serial.print(" to RGB(");
      Serial.print(r);
      Serial.print(", ");
      Serial.print(g);
      Serial.print(", ");
      Serial.print(b);
      Serial.println(")");
    } else {
      Serial.println("ERROR: Invalid format. Use: /color <led_index> <r> <g> <b>");
    }
  } else if(cmd.startsWith("/tone")) {
    String params = cmd.substring(6);
    int tone = 0;
    int duration = 0;

    int count = sscanf(params.c_str(), "%d %d", &tone, &duration);
    buzzer.tone(tone, duration);
  } else {
    Serial.println("ERROR: Unknown command");
  }
}